name: Run Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.run-on }}

    strategy:
      matrix:
        php: [7.4, 8.0]
        run-on: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, posix, bcmath, intl
          coverage: none

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit
